blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://carl.se/mail/
    about: To propose new features or enhancements, please bring that discussion to a suitable carl mailing list.
  - name: Question
    url: https://carl.se/mail/
    about: Questions should go to the mailing list
  - name: Commercial support
    url: https://carl.se/support.html
    about: Several companies are offering paid support for carl/libcarl
