#ifndef HEADER_CARLMSG_H
#define HEADER_CARLMSG_H
/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) 1998 - 2020, Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://carl.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ***************************************************************************/

#pragma __member_alignment __save
#pragma __nomember_alignment

/*                                                                          */
/* CARLMSG.H                                                                */
/*                                                                          */
/* SDL File Generated by VAX-11 Message V04-00 on 3-SEP-2008 13:33:54.09    */
/*                                                                          */
/* THESE VMS ERROR CODES ARE GENERATED BY TAKING APART THE CARL.H           */
/* FILE AND PUTTING ALL THE CARLE_* ENUM STUFF INTO THIS FILE,              */
/* CARLMSG.MSG.  AN .SDL FILE IS CREATED FROM THIS FILE WITH                */
/* MESSAGE/SDL.  THE .H FILE IS CREATED USING THE FREEWARE SDL TOOL         */
/* AGAINST THE .SDL FILE WITH SDL/ALPHA/LANG=CC COMMAND.                    */
/*                                                                          */
/* WITH THE EXCEPTION OF CARLE_OK, ALL OF THE MESSAGES ARE AT               */
/* THE ERROR SEVERITY LEVEL.  WITH THE EXCEPTION OF                         */
/* PEER_FAILED_VERIF, WHICH IS A SHORTENED FORM OF                          */
/* PEER_FAILED_VERIFICATION, THESE ARE THE SAME NAMES AS THE                */
/* CARLE_ ONES IN INCLUDE/CARL.H.  THE MESSAGE UTILITY MANUAL STATES        */
/* "THE COMBINED LENGTH OF THE PREFIX AND THE MESSAGE SYMBOL NAME CANNOT    */
/* EXCEED 31 CHARACTERS."  WITH A PREFIX OF FIVE THAT LEAVES US WITH 26     */
/* FOR THE MESSAGE NAME.                                                    */
/*                                                                          */
/* IF YOU UPDATE THIS FILE, UPDATE CARLMSG_VMS.H SO THAT THEY ARE IN SYNC   */
/*                                                                          */

#define CARL_FACILITY 3841
#define CARL_OK 251756553
#define CARL_UNSUPPORTED_PROTOCOL 251756562
#define CARL_FAILED_INIT 251756570
#define CARL_URL_MALFORMAT 251756578
#define CARL_OBSOLETE4 251756586
#define CARL_COULDNT_RESOLVE_PROXY 251756594
#define CARL_COULDNT_RESOLVE_HOST 251756602
#define CARL_COULDNT_CONNECT 251756610
#define CARL_WEIRD_SERVER_REPLY 251756618
#define CARL_FTP_WEIRD_SERVER_REPLY CARL_WEIRD_SERVER_REPLY
#define CARL_FTP_ACCESS_DENIED 251756626
#define CARL_OBSOLETE10 251756634
#define CARL_FTP_WEIRD_PASS_REPLY 251756642
#define CARL_OBSOLETE12 251756650
#define CARL_FTP_WEIRD_PASV_REPLY 251756658
#define CARL_FTP_WEIRD_227_FORMAT 251756666
#define CARL_FTP_CANT_GET_HOST 251756674
#define CARL_OBSOLETE16 251756682
#define CARL_FTP_COULDNT_SET_TYPE 251756690
#define CARL_PARTIAL_FILE 251756698
#define CARL_FTP_COULDNT_RETR_FILE 251756706
#define CARL_OBSOLETE20 251756714
#define CARL_QUOTE_ERROR 251756722
#define CARL_HTTP_RETURNED_ERROR 251756730
#define CARL_WRITE_ERROR 251756738
#define CARL_OBSOLETE24 251756746
#define CARL_UPLOAD_FAILED 251756754
#define CARL_READ_ERROR 251756762
#define CARL_OUT_OF_MEMORY 251756770
#define CARL_OPERATION_TIMEOUTED 251756778
#define CARL_OBSOLETE29 251756786
#define CARL_FTP_PORT_FAILED 251756794
#define CARL_FTP_COULDNT_USE_REST 251756802
#define CARL_OBSOLETE32 251756810
#define CARL_RANGE_ERROR 251756818
#define CARL_HTTP_POST_ERROR 251756826
#define CARL_SSL_CONNECT_ERROR 251756834
#define CARL_BAD_DOWNLOAD_RESUME 251756842
#define CARL_FILE_COULDNT_READ_FILE 251756850
#define CARL_LDAP_CANNOT_BIND 251756858
#define CARL_LDAP_SEARCH_FAILED 251756866
#define CARL_OBSOLETE40 251756874
#define CARL_FUNCTION_NOT_FOUND 251756882
#define CARL_ABORTED_BY_CALLBACK 251756890
#define CARL_BAD_FUNCTION_ARGUMENT 251756898
#define CARL_OBSOLETE44 251756906
#define CARL_INTERFACE_FAILED 251756914
#define CARL_OBSOLETE46 251756922
#define CARL_TOO_MANY_REDIRECTS 251756930
#define CARL_UNKNOWN_TELNET_OPTION 251756938
#define CARL_TELNET_OPTION_SYNTAX 251756946
#define CARL_OBSOLETE50 251756954
#define CARL_PEER_FAILED_VERIF 251756962
#define CARL_GOT_NOTHING 251756970
#define CARL_SSL_ENGINE_NOTFOUND 251756978
#define CARL_SSL_ENGINE_SETFAILED 251756986
#define CARL_SEND_ERROR 251756994
#define CARL_RECV_ERROR 251757002
#define CARL_OBSOLETE57 251757010
#define CARL_SSL_CERTPROBLEM 251757018
#define CARL_SSL_CIPHER 251757026
#define CARL_SSL_CACERT 251757034
#define CARL_BAD_CONTENT_ENCODING 251757042
#define CARL_LDAP_INVALID_URL 251757050
#define CARL_FILESIZE_EXCEEDED 251757058
#define CARL_USE_SSL_FAILED 251757066
#define CARL_SEND_FAIL_REWIND 251757074
#define CARL_SSL_ENGINE_INITFAILED 251757082
#define CARL_LOGIN_DENIED 251757090
#define CARL_TFTP_NOTFOUND 251757098
#define CARL_TFTP_PERM 251757106
#define CARL_REMOTE_DISK_FULL 251757114
#define CARL_TFTP_ILLEGAL 251757122
#define CARL_TFTP_UNKNOWNID 251757130
#define CARL_REMOTE_FILE_EXISTS 251757138
#define CARL_TFTP_NOSUCHUSER 251757146
#define CARL_CONV_FAILED 251757154
#define CARL_CONV_REQD 251757162
#define CARL_SSL_CACERT_BADFILE 251757170
#define CARL_REMOTE_FILE_NOT_FOUND 251757178
#define CARL_SSH 251757186
#define CARL_SSL_SHUTDOWN_FAILED 251757194
#define CARL_AGAIN 251757202
#define CARL_SSL_CRL_BADFILE 251757210
#define CARL_SSL_ISSUER_ERROR 251757218
#define CARL_CARL_LAST 251757226

#pragma __member_alignment __restore

#endif /* HEADER_CARLMSG_H */
