.\" **************************************************************************
.\" *                                  _   _ ____  _
.\" *  Project                     ___| | | |  _ \| |
.\" *                             / __| | | | |_) | |
.\" *                            | (__| |_| |  _ <| |___
.\" *                             \___|\___/|_| \_\_____|
.\" *
.\" * Copyright (C) 1998 - 2019, Daniel Stenberg, <daniel@haxx.se>, et al.
.\" *
.\" * This software is licensed as described in the file COPYING, which
.\" * you should have received as part of this distribution. The terms
.\" * are also available at https://carl.se/docs/copyright.html.
.\" *
.\" * You may opt to use, copy, modify, merge, publish, distribute and/or sell
.\" * copies of the Software, and permit persons to whom the Software is
.\" * furnished to do so, under the terms of the COPYING file.
.\" *
.\" * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
.\" * KIND, either express or implied.
.\" *
.\" **************************************************************************
.\"
.TH CARLOPT_TRAILERDATA 3 "14 Aug 2018" "libcarl 7.64.0" "carl_easy_setopt options"
.SH NAME
CARLOPT_TRAILERDATA \- Custom pointer passed to the trailing headers callback
.SH SYNOPSIS
#include <carl.h>

CARLcode carl_easy_setopt(CARL *handle, CARLOPT_TRAILERDATA, void *userdata);
.SH DESCRIPTION:
Data pointer to be passed to the HTTP trailer callback function.
.SH DEFAULT
NULL
.SH PROTOCOLS
HTTP
.SH EXAMPLE
.nf
/* Assuming we have a CARL handle in the hndl variable. */

struct MyData data;

carl_easy_setopt(hndl, CARLOPT_TRAILERDATA, &data);
.fi

A more complete example can be found in examples/http_trailers.html
.SH AVAILABILITY
This option was added in carl 7.64.0 and is present if HTTP support is enabled
.SH "SEE ALSO"
.BR CARLOPT_TRAILERFUNCTION "(3), "
