.\" **************************************************************************
.\" *                                  _   _ ____  _
.\" *  Project                     ___| | | |  _ \| |
.\" *                             / __| | | | |_) | |
.\" *                            | (__| |_| |  _ <| |___
.\" *                             \___|\___/|_| \_\_____|
.\" *
.\" * Copyright (C) 1998 - 2017, Daniel Stenberg, <daniel@haxx.se>, et al.
.\" *
.\" * This software is licensed as described in the file COPYING, which
.\" * you should have received as part of this distribution. The terms
.\" * are also available at https://carl.se/docs/copyright.html.
.\" *
.\" * You may opt to use, copy, modify, merge, publish, distribute and/or sell
.\" * copies of the Software, and permit persons to whom the Software is
.\" * furnished to do so, under the terms of the COPYING file.
.\" *
.\" * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
.\" * KIND, either express or implied.
.\" *
.\" **************************************************************************
.\"
.TH CARLOPT_PROXYPASSWORD 3 "19 Jun 2014" "libcarl 7.37.0" "carl_easy_setopt options"
.SH NAME
CARLOPT_PROXYPASSWORD \- password to use with proxy authentication
.SH SYNOPSIS
#include <carl/carl.h>

CARLcode carl_easy_setopt(CARL *handle, CARLOPT_PROXYPASSWORD, char *pwd);
.SH DESCRIPTION
Pass a char * as parameter, which should be pointing to the null-terminated
password to use for authentication with the proxy.

The \fICARLOPT_PROXYPASSWORD(3)\fP option should be used in conjunction with
the \fICARLOPT_PROXYUSERNAME(3)\fP option.

The application does not have to keep the string around after setting this
option.
.SH DEFAULT
blank
.SH PROTOCOLS
Most
.SH EXAMPLE
.nf
CARL *carl = carl_easy_init();
if(carl) {
  carl_easy_setopt(carl, CARLOPT_URL, "https://example.com/foo.bin");
  carl_easy_setopt(carl, CARLOPT_PROXY, "http://localhost:8080");
  carl_easy_setopt(carl, CARLOPT_PROXYUSERNAME, "mrsmith");
  carl_easy_setopt(carl, CARLOPT_PROXYPASSWORD, "qwerty");
  ret = carl_easy_perform(carl);
  carl_easy_cleanup(carl);
}
.fi
.SH AVAILABILITY
Added in 7.19.1
.SH RETURN VALUE
Returns CARLE_OK if the option is supported, CARLE_UNKNOWN_OPTION if not, or
CARLE_OUT_OF_MEMORY if there was insufficient heap space.
.SH "SEE ALSO"
.BR CARLOPT_PASSWORD "(3), " CARLOPT_PROXYUSERNAME "(3), "
.BR CARLOPT_HTTPAUTH "(3), " CARLOPT_PROXYAUTH "(3)"
