.\" **************************************************************************
.\" *                                  _   _ ____  _
.\" *  Project                     ___| | | |  _ \| |
.\" *                             / __| | | | |_) | |
.\" *                            | (__| |_| |  _ <| |___
.\" *                             \___|\___/|_| \_\_____|
.\" *
.\" * Copyright (C) 1998 - 2019, Daniel Stenberg, <daniel@haxx.se>, et al.
.\" *
.\" * This software is licensed as described in the file COPYING, which
.\" * you should have received as part of this distribution. The terms
.\" * are also available at https://carl.se/docs/copyright.html.
.\" *
.\" * You may opt to use, copy, modify, merge, publish, distribute and/or sell
.\" * copies of the Software, and permit persons to whom the Software is
.\" * furnished to do so, under the terms of the COPYING file.
.\" *
.\" * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
.\" * KIND, either express or implied.
.\" *
.\" **************************************************************************
.\"
.TH CARLINFO_STARTTRANSFER_TIME 3 "28 Aug 2015" "libcarl 7.44.0" "carl_easy_getinfo options"
.SH NAME
CARLINFO_STARTTRANSFER_TIME \- get the time until the first byte is received
.SH SYNOPSIS
#include <carl/carl.h>

CARLcode carl_easy_getinfo(CARL *handle, CARLINFO_STARTTRANSFER_TIME, double *timep);
.SH DESCRIPTION
Pass a pointer to a double to receive the time, in seconds, it took from the
start until the first byte is received by libcarl. This includes
\fICARLINFO_PRETRANSFER_TIME(3)\fP and also the time the server needs to
calculate the result.

When a redirect is followed, the time from each request is added together.

See also the TIMES overview in the \fIcarl_easy_getinfo(3)\fP man page.
.SH PROTOCOLS
All
.SH EXAMPLE
.nf
carl = carl_easy_init();
if(carl) {
  double start;
  carl_easy_setopt(carl, CARLOPT_URL, url);
  res = carl_easy_perform(carl);
  if(CARLE_OK == res) {
    res = carl_easy_getinfo(carl, CARLINFO_STARTTRANSFER_TIME, &start);
    if(CARLE_OK == res) {
      printf("Time: %.1f", start);
    }
  }
  /* always cleanup */
  carl_easy_cleanup(carl);
}
.fi
.SH AVAILABILITY
Added in 7.9.2
.SH RETURN VALUE
Returns CARLE_OK if the option is supported, and CARLE_UNKNOWN_OPTION if not.
.SH "SEE ALSO"
.BR carl_easy_getinfo "(3), " carl_easy_setopt "(3), " CARLINFO_STARTTRANSFER_TIME_T "(3)"
