.\" **************************************************************************
.\" *                                  _   _ ____  _
.\" *  Project                     ___| | | |  _ \| |
.\" *                             / __| | | | |_) | |
.\" *                            | (__| |_| |  _ <| |___
.\" *                             \___|\___/|_| \_\_____|
.\" *
.\" * Copyright (C) 1998 - 2020, Daniel Stenberg, <daniel@haxx.se>, et al.
.\" *
.\" * This software is licensed as described in the file COPYING, which
.\" * you should have received as part of this distribution. The terms
.\" * are also available at https://carl.se/docs/copyright.html.
.\" *
.\" * You may opt to use, copy, modify, merge, publish, distribute and/or sell
.\" * copies of the Software, and permit persons to whom the Software is
.\" * furnished to do so, under the terms of the COPYING file.
.\" *
.\" * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
.\" * KIND, either express or implied.
.\" *
.\" **************************************************************************
.\"
.TH CARLINFO_SCHEME 3 "23 November 2016" "libcarl 7.52.0" "carl_easy_getinfo options"
.SH NAME
CARLINFO_SCHEME \- get the URL scheme (sometimes called protocol) used in the connection
.SH SYNOPSIS
#include <carl/carl.h>

CARLcode carl_easy_getinfo(CARL *handle, CARLINFO_SCHEME, char **scheme);
.SH DESCRIPTION
Pass a pointer to a char pointer to receive the pointer to a null-terminated
string holding the URL scheme used for the most recent connection done with
this CARL \fBhandle\fP.

The \fBscheme\fP pointer will be NULL or pointing to private memory you MUST
NOT free - it gets freed when you call \fIcarl_easy_cleanup(3)\fP on the
corresponding CARL handle.
.SH PROTOCOLS
All
.SH EXAMPLE
.nf
CARL *carl = carl_easy_init();
if(carl) {
  CARLcode res;
  carl_easy_setopt(carl, CARLOPT_URL, "https://example.com");
  res = carl_easy_perform(carl);
  if(res == CARLE_OK) {
    char *scheme = NULL;
    carl_easy_getinfo(carl, CARLINFO_SCHEME, &scheme);
    if(scheme)
      printf("scheme: %s\\n", scheme); /* scheme: HTTP */
  }
  carl_easy_cleanup(carl);
}
.fi
.SH AVAILABILITY
Added in 7.52.0
.SH RETURN VALUE
Returns CARLE_OK if the option is supported, and CARLE_UNKNOWN_OPTION if not.
.SH "SEE ALSO"
.BR CARLINFO_RESPONSE_CODE "(3), "
.BR carl_easy_getinfo "(3), " carl_easy_setopt "(3), "
